<template>
  <div class="m-10 p-5 text-xs">
    Icons Attributes: From
    <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
    <div>
      Authors
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/<?=_('authors/')?>freepik"
        title="Freepik"
        >Freepik</a
      >
    </div>
    <div>
      &bull;&nbsp;<a href="https://www.flaticon.com/authors/srip" title="srip"
        >srip</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/smashicons"
        title="Smashicons"
        >Smashicons</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/kiranshastry"
        title="Kiranshastry"
        >Kiranshastry</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/ultimatearm"
        title="ultimatearm"
        >ultimatearm</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/eucalyp"
        title="Eucalyp"
        >Eucalyp</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/icongeek26"
        title="Icongeek26"
        >Icongeek26</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/pause08"
        title="Pause08"
        >Pause08</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/prettycons"
        title="prettycons"
        >prettycons</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/<?=_('authors/')?>itim2101"
        title="itim2101"
        >itim2101</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/surang"
        title="surang"
        >surang</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/flat-icons"
        title="Flat Icons"
        >Flat Icons</a
      >
    </div>
    <div>
      &bull;&nbsp;<a href="https://www.flaticon.com/authors/bqlqn" title="bqlqn"
        >bqlqn</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/monkik"
        title="monkik"
        >monkik</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/itim2101"
        title="itim2101"
        >itim2101</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/phatplus"
        title="phatplus"
        >phatplus</a
      >
    </div>
    <div>
      &bull;&nbsp;<a
        href="https://www.flaticon.com/authors/prettycons"
        title="prettycons"
        >prettycons</a
      >
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style></style>
